---
title: "Old"
author: "Brian Callander"
date: "August 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sparse Splines

```{r}
m_splines_milad <- stan_model('splines_milad.stan', model_name = 'splines_milad')
m_splines_milad
```

```{r}
f_splines_milad <- sampling(
  m_splines_milad,
  data = df %>% compose_data(X = X, 
                             k= dim(X)[2], 
                             sigma_scale = 1,
                             b0_scale = 1,
                             s_scale = 0.5
                            ),
  iter = 4000,
  warmup = 2000
)
```

```{r}
library(broom)
summary(f_splines_milad, pars = c('mu'))$summary %>% 
  tidy() %>% 
  select(mu = mean, conf.low = X2.5., conf.high = X97.5.) %>% 
  mutate(idx = 1:n()) %>% 
  inner_join(df, by = 'idx') %>% 
  ggplot(aes(x = hour, y = kph)) +
  geom_vline(xintercept = knots$hour, colour = 'orange', size = 1, alpha = 0.2) +
  geom_point(alpha = 0.4) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = 'skyblue', alpha = 0.5) +
  geom_line(aes(x = hour, y = mu), colour = 'dark blue') +
  NULL


```



```{r spline_shrink_prior_predictive}
draw_1_sspline <- function(X, b0_scale = 1, s_scale = 0.1, sigma_scale = 1) {

  # dimensions of the model
  N <- nrow(X)
  K <- ncol(X)
  
  # average kph
  v <- rgamma(1, v_prior$shape, v_prior$rate)

  # spline priors
  b0 <- abs(rcauchy(K, 0, b0_scale))
  s <- abs(rcauchy(1, 0, s_scale))
  b <- rnorm(K, 0, s * b0)
  
  # mean and standard deviation of observed kph
  mu <- v * exp(c(X %*% b))
  sigma <- abs(rcauchy(1, 0, sigma_scale))
  
  # shape/rate 
  rate <- mu / (sigma^2)
  shape <-  rate * mu
  
  kph = rgamma(N, shape, rate)
  
  # draws from prior predictive kph distribution
  list(
    v = v,
    b0 = b0,
    mu = mu,
    sigma = sigma,
    rate = rate,
    shape = shape,
    kph = kph
  ) 
}

draw_1_sspline(X, s_scale = 1, b0_scale = 0.1) %>% 
  magrittr::extract(c('mu', 'kph')) %>%
  as_tibble() %>% 
  mutate(hour = df$hour) %>%
  ggplot(aes(x = hour)) +
  geom_line(aes(y = mu), colour = 'orange') +
  geom_point(aes(y = kph), alpha = 0.3) +
  scale_y_continuous(limits = c(0, 50)) +
  NULL

```

```{r}
df %>% 
  mutate(draw = draw_1_sspline(X, s_scale = 0.35, b0_scale = 0.7)$kph) %>% 
  ggplot(aes(x = hour, y = draw)) +
  geom_point() +
  scale_y_continuous(limits = c(0, 50))
```


## Horseshoe

```{r}
m_hs <- stan_model('splines_horseshoe.stan', model_name = 'horseshoe_splines')
m_hs
```
```{r}
df %>% 
  filter(cadence > 80) %>% 
  ggplot(aes(x = cadence, y = kph)) +
  geom_point()
```

```{r}
reduce_knots <- function(knots, interval = 5) {
  knots %>% 
    distinct(time, .keep_all = TRUE) %>% 
    arrange(time) %>% 
    filter(time - lag(time, default = -interval) >= interval)
}

knots <- laps %>% reduce_knots() %>% 
  bind_rows(low_cadence %>% reduce_knots()) %>% 
  bind_rows(qknots %>% reduce_knots()) %>% 
  reduce_knots(10) %>%
  arrange(time) 

knots

X <- df %>% 
  pull(hour) %>% 
  make_spline_matrix(knots = knots$hour, intercept = TRUE)

dim(X)
  
df %>% 
  ggplot(aes(x = hour, y = kph)) +
  geom_point(alpha = 0.5) +
  geom_vline(xintercept = knots$hour, colour = 'orange', alpha = 0.5) +
  NULL
```



```{r}
f_hs <- sampling(
  m_hs,
  data = df %>% 
          compose_data(X = X, 
                       k = ncol(X),
                       l_scale = 1,
                       t_scale = 0.1,
                       sigma_scale = 1
                      ),
  iter = 5000,
  warmup = 1500
) %>% recover_types(df)
```
```{r}
f_hs <- f_hs %>% recover_types(df)
```

```{r}
p_hs <- extract(f_hs, pars = c('mu'))$mu %>% 
  apply(2, quantile, probs = c(0.1, 0.5, 0.9)) %>% 
  t() %>% 
  as_tibble() %>% 
  set_names(paste('mu', colnames(.), sep = '_')) %>% 
  cbind(df %>% select(idx, time, hour, kph))

p_hs

```


```{r}
extract(f_hs, pars = c('shape', 'rate')) %>% 
  map(apply, 2, quantile, probs = c(0.1, 0.5, 0.9)) %>% 
  map(t) %>% 
  map(as_tibble) %>% 
  reduce(rbind) %>% 

p_hs

```

```{r}
interval <- 0.3
start <- 0.2
p_hs %>% 
  # filter(start < hour & hour < start + interval) %>%
  ggplot(aes(x = hour, y = kph)) +
  # geom_vline(xintercept = knots$hour, colour = 'orange', alpha = 0.5) +
  geom_ribbon(aes(ymin = `mu_10%`, ymax = `mu_90%`), fill = 'orange', alpha = 0.5) +
  geom_line(aes(x = hour, y = `mu_50%`)) +
  geom_point(alpha = 0.25) +
  NULL

```

```{r}
f_hs %>% 
  spread_samples(b[idx]) %>% 
  ggplot(aes(y = fct_rev(estimate), x = b)) +
  geom_pointintervalh()

```

```{r}
library(mgcv)
```

```{r}
f <- gam(
  kph ~ s(hour, k = 60) + cut(cadence, c(-1, 30, 70, 200)),
  data = df,
  gamily = Gamma(link = 'exp')
)

predict(f, type = 'response', se.fit = TRUE) %>% 
  as_tibble() %>% 
  cbind(df) %>% 
  ggplot(aes(x = hour, y = fit)) +
  geom_ribbon(aes(ymin = fit - 2 * se.fit, ymax = fit + 2 * se.fit), fill = 'orange', alpha = 0.5) +
  geom_line() +
  geom_point(aes(y = kph), alpha = 0.3) +
  NULL

```

```{r}
predict(f, type = 'response', se.fit = TRUE) %>% 
  as_tibble()
```
```{r}
f_hs %>% 
  spread_draws(b[idx])
```

## Finnish Horseshoe

```{r}
m_fhs <- stan_model('splines_horseshoe_finnish.stan', model_name = 'finnish_horseshoe_splines')
m_fhs
```
```{r}
dim(X)
```

```{r}
f_fhs <- sampling(
  m_fhs,
  data = df %>% 
          compose_data(X = X, 
                       k = ncol(X),
                       k0 = 7,
                       s = 0.6,
                       nu = 2,
                       sigma_scale = 1
                      ),
  iter = 5000,
  warmup = 1500
  # control = list(adapt_delta = 0.95)
) %>% recover_types(df)
```

```{r}
p_fhs <- extract(f_fhs, pars = c('mu'))$mu %>% 
  apply(2, quantile, probs = c(0.1, 0.5, 0.9)) %>% 
  t() %>% 
  as_tibble() %>% 
  set_names(paste('mu', colnames(.), sep = '_')) %>% 
  cbind(df %>% select(idx, time, hour, kph))

p_fhs

```
```{r}
shinystan::launch_shinystan(f_fhs)
```



```{r}
interval <- 0.3
start <- 0.2
p_fhs %>% 
  # filter(start < hour & hour < start + interval) %>%
  ggplot(aes(x = hour, y = kph)) +
  # geom_vline(xintercept = knots$hour, colour = 'orange', alpha = 0.5) +
  geom_ribbon(aes(ymin = `mu_10%`, ymax = `mu_90%`), fill = 'orange', alpha = 0.5) +
  geom_line(aes(x = hour, y = `mu_50%`)) +
  geom_point(alpha = 0.25) +
  NULL

```


## Other

